### ISSUE TITLE
Let me test your twrp.img

### ISSUE THREAD

**Issue by cata332** [ImRyujinnn/recovery_device_xiaomi_agate#1]
Let me test your twrp.img

**Comment by cata332** [comment]
@ImRyujinnn Yes...boot loooooop to twrp !
Decription is working well !
Mount working partial !
I will love to test next build...send me the next build for testing
Thank you.

**Comment by ImRyujinnn** [comment]
@cata332 if you want to test next build you can pm me on telegram😀

**Comment by cata332** [comment]
@ImRyujinnn OK...but you forget to give to me your telegram ! 👍

**Comment by ImRyujinnn** [comment]
@ImRyujinnn t.me/sevyroth

**Comment by ImRyujinnn** [comment]
@cata332 t.me/sevyroth

**Comment by cata332** [comment]
> @cata332 t.me/sevyroth

https://t.me/DarckKMaster    i just send you a msg !
This mesage wil get deleted in 5 min......
